apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: build-kitchen
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: build-kitchen
    app.kubernetes.io/part-of: build-kitchen
  name: build-kitchen
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: build-kitchen
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: build-kitchen
    spec:
      containers:
      - image: java-quarkus-image:latest
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 8080
        resources:
          requests:
            cpu: 500m
            memory: 1100Mi
status: {}
